project:
  type: website
  output-dir: docs

website:
  title: "Monash NUMBATs"
  navbar:
    background: "#006dae"
    left:
      - href: people/index.qmd
        text: People
      - href: posts/index.qmd
        text: Posts
      - projects.qmd
      - href: hacky-hour/index.qmd
        text: "Hacky Hour"
      - events.qmd
      - href: workshops/index.qmd
        text: Workshops
      - href: courses.qmd
        text: Courses
      - href: about.qmd
        text: About
      - contact.qmd

date-format: "D MMMM YYYY"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex

execute:
  freeze: auto
resource:
  - CNAME
