---
title: "About NUMBATs"
---

NUMBATs is the name for our research group, Non-Uniform Monash Business Analytics Team, in the [Econometrics and Business Statistics Department](https://www.monash.edu/business/ebs). We meet regularly to openly exchange and discuss research ideas and activity in an actively supportive and creative environment. People outside the group are welcome to attend, and can sign up to receive notifications about topics for each meeting, or check the calendar on the web site.

Our mission is to advance methodology for making data analysis easier. We develop new techniques for statistical modeling and visualisation, and work hard to make these available to the general public by distributing open source software, mostly using R.

It is also our goal to raise awareness of Australian fauna and flora, particularly many of the beautiful endangered species. For example, in reality, numbats are insectivores, mostly found in Western Australia, and we encourage you to contribute to the conservation efforts by donating or purchasing products from [Project Numbat](http://www.numbat.org.au/).
