---
title: Courses
---

The Business Analytics group has two main educational offerings, with details from the handbook at:

-  [Bachelor of Commerce (Major in Business Analytics)](https://handbook.monash.edu/current/aos/BUSANLMJ01)
- [Master of Business Analytics](https://handbook.monash.edu/current/courses/B6022)

These degrees provide students with a advanced knowledge in applied statistics and data science, with a focus on open source software and open data. With this knowledge you can equip yourself with computational statistical tools to understand the world around you in the face of uncertainty.

Some of the unit websites are:

- [ETC5510 Introduction to data analysis (2020 original)](https://mida.numbat.space)
- [ETC5512 Wild-caught data](https://wcd.numbat.space)
- [ETC5513 Reproducible and collaborative practices](https://rcp.numbat.space)
- [ETC5521 Diving deeply into data exploration](https://ddde.numbat.space)
- [ETC5523 Communicating with data](https://cwd.numbat.space)
- [ETC5500 Applied forecasting](https://af.numbat.space)
- [ETC5250 Introduction to machine learning](https://iml.numbat.space)
- [ETC5450 Advanced R programming](https://arp.numbat.space)

A full list of current topics for the B.Comm BA major can be found [here](unit_information/BComm_unit_summaries.pdf) and the MBAt program can be seen [here](unit_information/MBAt_unit_summaries.pdf). 

## Additional Resources

### Fresh and local data

We have a teaching philosophy to use fresh and local data, as defined in [these slides](https://wcd.numbat.space/lectures/lecture-01.html#29). These resources can be found at [this website](data.html).

## Style guide

- [Templates](https://github.com/quarto-monash)
    - Website: `quarto use template quarto-monash/unit`
    - Slides: `quarto use template quarto-monash/presentation`
- We recommend following [Tidyverse style guide](https://style.tidyverse.org) for R code

## Introductory R lessons

A set of self-paced lessons to get started with R can be found at [https://startr.numbat.space](https://startr.numbat.space).

## Creating a kaggle competition

- [Instructions and past data examples](https://ebsmonash.shinyapps.io/kaggle_instructions/)