---
title: "Do you need some analytics help? Maybe our internship program is for you!"
author:
  - Dan Simpson
date: "2022-02-18T00:00:00Z"
lastMod: "2022-02-18T00:00:00Z"
output: blogdown::html_page
categories:
  - data visualisation
  - statistics
  - machine learning
  - teaching
tags:
  - R
  - teaching
  - data visualisation
  - machine learning
  - statistical models
summary: "Do you have a data analysis task and want some help with it? We have a lot of Masters students who might be able assist."
---





We have a new Masters in Business Analytics in the Econometrics and Business Statistics department in the Monash Business School and in the final semester of the program, the students have an option to do an internship. The aim is to give our students some work experience in analytics and to build links with various companies, institutions, and charities.

The program is highly selective and has an annual intake of around 50-60 student. The majority of our students will undertake the internship component of the program.

The students will have advanced R and data science skills. As well as having experience with various types of statistical analysis and machine learning, they have strong training in modern techniques for building reproducible analysis pipelines, automated reporting, and building interactive tools for understanding data.

The students will also meet regularly throughout the project with an academic from
Monash and their fellow students to discuss problem solving and analysis techniques
that are relevant to their projects.
Previous students have worked on a diverse selection of projects including

- Migration forecasting
- Analytics for a health food shop
- Data journalism
- Forecasting bushfire risk
- Building learning resources to help people learn R
- Developing contact strategies for a bank to minimise custormer churn
- Fraud detection for a health insurer
- Estimating risk of hospitalisation
- Building an analytics dashboard for a real estate company

### What you need to have

**A project.**  Suitable projects  should involve a substantial data analysis or modelling component, and should address a problem of interest to the sponsoring organization. They should take 25-30 working days to complete. Students can work in teams as part of the project.
The project can take place any time during the year, but most students will be available from late July to the end of October.
It is not a requirement that students are reimbursed for this work, although some organizations choose to pay students a nominal wage during their internship^[Monash will provide insurance for all students provided they are not classified as employees.].

One important restriction on the project is that it must fit with our assessment structure for the unit. We are asking the students to produce a 10,000 word report^[This may be anonymised, deidentified, or redacted as required, as long as it is still possible to assess the student's work.] on their work (which may include interactive apps or software packages that they have developed if appropriate), give a short talk, and provide access to their analysis code, ideally in a private github repository^[We are happy to discuss other options for assessing the code if using github or sharing the code is not feasible for your company. This should be decided before the internship begins.]. The data does not need to be available to Monash.


**A supervisor.** Each student must have a designated supervisor who will meet them (at a minimum) once per week during their internship. They will set the parameters of the project and will need to complete a short form indicating the student's performance at the end of the project.


### Any further questions?

If you have any further questions please contact me at [dan.simpson@monash.edu](mailto:dan.simpson@monash.edu). I'm happy to organize a follow up phone call, video call, or (if possible) in person meeting to discuss this further.

### Spread the word!

Please share this with anyone you think may be interested. We also have this information available [as a PDF document](Monash_EBS_Internship_Flyer_2022.pdf).
