---
title: "NUMBAT Workshops"
---

# About

These workshops are designed to help develop data analysis and computing skills in the Monash and broader community. Workshops will be hands-on and primarily focus on using R. Most workshops will be hybrid, in-person for the Monash community and also with the possibility to join on zoom. They will be taught by experts on the topics from the [NUMBATs group](https://numbat.space/people/). 

Workshops are organised along three themes: 

- <span style="color: #3B99B1;">**Learning from data**</span>: extracting data from various sources, tidying, wrangling, modelling, analysis, exploratory data graphics.
- <span style="color: #56B29E;">**Data science productivity**</span>: reproducibility, collaboration, literate programming, efficient coding, sharing code.
- <span style="color: #9FC095;">**Communicating with data**</span>: effective visualisation, storytelling, engineering interactive web apps, publishing software.

Workshops are also grade on three levels: 

- <span style="color: #EACB2B;">**Beginner**</span>: A basic knowledge of R, and using RStudio, is all that is needed to understand the content.
- <span style="color: #E87700;">**Intermediate**</span>: Along with a basic knowledge, some additional experience such as comfortable with the content of [R4DS](https://r4ds.hadley.nz).
- <span style="color: #F5191C;">**Advanced**</span>: This level is for experienced analysts wishing to advanced their level of understanding on particular specialty areas. 

# Make a suggestion

If you have requests for topics to be covered, you can provide this feedback through this [sheet](https://forms.gle/BLdEp9KMqmvstgWb7).

# Schedule for 2025

```{r}
#| echo: false
#| message: false
#| error: false
#| warning: false
library(readr)
library(dplyr)
library(gt)
library(glue)
library(stringr)
library(lubridate)
library(colorspace)
schedule <- read_csv("schedule.csv")
regtext <- "Sign up"
schedule <- schedule |>
  #mutate(date = ifelse(!is.na(dmy(date)), dmy(date), date)) |>
  mutate(titlelink = ifelse(is.na(link), title, glue("[{title}]({link})"))) |>
  mutate(reglink = ifelse(registration == "TBA", " ",
                          glue("[{regtext}]({registration})"))) |>
  mutate(reglink = ifelse(str_detect(registration, "available"),
                          registration,
                          reglink)) |>
  mutate(topic = factor(topic, levels = c("Learning from data", 
                                          "Communicating with data", 
                                          "Data science productivity"))) |>
  mutate(level = factor(level, levels = c("Beginner", 
                                          "Intermediate", 
                                          "Advanced")))
topic_clr <- divergingx_hcl(7, 
    palette = "Zissou 1")[c(1,2,3)]
level_clr <- divergingx_hcl(7, 
    palette = "Zissou 1")[c(4,6,7)] #sequential_hcl(3, 
    #palette = "Emrld", rev = TRUE, alpha=0.5)
schedule |>
  #arrange(desc(date)) |>
  select(date, time, reglink, titlelink, instructor, location, topic, level) |>
  gt() |>
    gt::fmt_markdown(columns = c(titlelink, reglink)) |>
    cols_label(titlelink = "title") |> 
    gt::cols_width(
      #month ~ px(50),
      date ~ px(200),
      time ~ px(100),
      reglink ~ px(250),
      titlelink ~ px(200),
      instructor ~ px(100),
      location ~ px(100),
      topic ~ px(150),
      level ~ px(100)) |>
  tab_style(
    style = cell_text(size = "small"),
    locations = cells_body(columns = date:time)
  ) |>
  tab_style(
    style = cell_text(size = "smaller"),
    locations = cells_body(columns = instructor:level)
  ) |>
  tab_style(cell_text(size="large"),
            locations = cells_body(columns = reglink:titlelink)) |>
  data_color(columns = topic, 
             method = "factor",
             target_columns = titlelink:topic,
             palette = topic_clr) |>
  data_color(columns = level, 
             method = "factor",
             palette = level_clr) |>
  opt_row_striping(row_striping = FALSE) |>
  cols_label(
    date = "Date",
    time = "Time", 
    reglink = "Register",
    titlelink = "Title",
    instructor = "Instructor",
    location = "Room",
    topic = "Category",
    level = "") |> 
  cols_align("left")
```

You can add the full range of NUMBAT events to your calendar via [iCal](https://calendar.google.com/calendar/ical/t0umouvaoo3h62kcfcj7vcfck8%40group.calendar.google.com/public/basic.ics) or [Google calendar](https://calendar.google.com/calendar?cid=dDB1bW91dmFvbzNoNjJrY2Zjajd2Y2ZjazhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ).


# Self-paced materials 

The web resource [https://startr.numbat.space](https://startr.numbat.space) provides these self-paced learning modules:

- Getting started with R
- Tidy data analysis
- Statistical modelling
- Quarto basics, for reproducible publications 

# Other workshops 

## Monash

[eResearch maintains a list](https://docs.erc.monash.edu/training/) of other groups offering workshops and links to the workshops on campus. These are primarily run by eResearch and the [Monash Bioinformatics Platform](https://www.monash.edu/researchinfrastructure/bioinformatics/training). The [eResearch newsletter](https://mailchi.mp/e0c3342ff59a/eresearch-march-2025-newsletter) provides regular details, also. 

## Elsewhere

The [Statistical Society of Australia](https://www.statsoc.org.au/Events-calendar), in particular the Statistical Computing and Visualisation Section, regularly run workshops which are listed on their events page.

