---
title: "Can our Masters students help you?"
author: Rob J Hyndman
date: "2021-03-05T00:00:00Z"
lastMod: "2021-03-05T00:00:00Z"
categories:
  - data visualisation
  - statistics
  - machine learning
  - teaching
tags:
  - R
  - teaching
  - data visualisation
  - machine learning
  - statistical models
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Do you have a data analysis task and want some help with it? We have a lot of Masters students who might be able assist.

## Masters of Business Analytics students

Our Masters of Business Analytics students are well-trained in the entire workflow of data analysis including data collection, munging, exploratory analysis, modelling and reporting. Our program is based around R, so all students should have relatively advanced R skills. Some of them may also have Python, SQL and other language skills. Our students are also taught to use modern reproducible practices and are comfortable with using git, Rmarkdown, etc.

Towards the end of their degree, our students take on an internship in which they work with an organization on a data analysis project. The project is for a minimum of 225 hours (30 working days) to be undertaken at a time suitable to the organization and the student. This does not have to be done during normal teaching periods. Normally, the majority of the hours are to be spent on site (or virtually) embedded in the organization. It is not a requirement that students are reimbursed for this work, although some organizations choose to pay students a nominal wage during their internship. (Monash will provide insurance for all students provided they are not classified as employees.)

Suitable projects should involve a substantial data analysis or modelling component, and should address a problem of interest to the sponsoring organization. At the start of the program, the organization, Monash University and the student must all agree on a suitable project.

Students will write a report of about 30 pages outlining the analysis they have undertaken. A copy of this report will be provided to the sponsoring organization, along with all the code that was produced as part of the analysis.

Each student will need a supervisor from the sponsoring organization who must meet with the student at least weekly to ensure the student is on track. All participating students will also meet regularly (every few weeks) with a Monash University academic who can help with any technical issues.

At the conclusion of the project, the supervisor will need to provide a one page report to Monash University on the student's performance.

If you think this might be of interest to your organization, please contact [Professor Rob Hyndman](mailto:Rob.Hyndman@monash.edu).